name: CityDAO Raffle

on:
  workflow_dispatch:
    inputs:
      input_name:
        description: 'The file name for input'
        required: true
        default: 'input.csv'

env:
  ALCHEMY_API: ${{ secrets.ALCHEMY_API }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: npm ci
      - name: Testing 🧪
        run: npm run test:integration
      - uses: actions/upload-artifact@v3
        with:
          name: winners
          path: output.csv