name: CityDAO Raffle Scheduled Testing

on:
  schedule:
    - cron: "0 */3 * * *"

env:
  ALCHEMY_API: ${{ secrets.ALCHEMY_API }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: npm ci
      - name: Testing 🧪
        run: npm run test:integration
      - name: Start Raffle 🎟
        run: node index.js --winners 125 --input input.csv
      - uses: actions/upload-artifact@v3
        with:
          name: winners
          path: output.csv